mutation GetCombinationResult($one: String!, $two: String!) {
  combination(input: { one: $one, two: $two }) {
    getCombinationPayload {
      combinationResult {
        hash
        elementOne
        elementTwo
        result
      }
    }
  }
}

query GetInfCombination($combinationId: String!) {
  infCombination(combinationId: $combinationId) {
    resultElement {
      elementId
      name
      emoji
    }
  }
}


mutation CreateInfCombination($one: String!, $two: String!) {
  createInfCombination(input: { one: $one, two: $two }) {
    infCombination {
      resultElement {
        elementId
        name
        emoji
      }
    }
  }
}