query GetConversations {
    conversations {
        conversationId
        messageId
        parentId
        userId
        text
        from
        timestamp
    }
}

query GetSimpleTest {
    simpleTest
}

query GetUserId {
    userId
}